# Generated by Django 3.2.24 on 2024-05-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='treatmentsitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=25)),
                ('charges', models.CharField(max_length=25)),
                ('procedurecode', models.CharField(max_length=25)),
                ('Duration', models.IntegerField()),
                ('Session', models.CharField(max_length=50)),
            ],
        ),
    ]
