# Generated by Django 3.2.24 on 2024-05-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_drugitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintsitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('boxsize', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('purchase', models.CharField(max_length=50)),
                ('packingsize', models.CharField(max_length=50)),
                ('taxable', models.CharField(max_length=50)),
                ('recorder', models.CharField(max_length=50)),
                ('batchno', models.CharField(max_length=50)),
                ('salesrate', models.CharField(max_length=50)),
                ('deviceserialsnumber', models.CharField(max_length=50)),
                ('hsncode', models.CharField(max_length=50)),
            ],
        ),
    ]
