# Generated by Django 3.2.24 on 2024-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_add_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addobservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=50)),
            ],
        ),
    ]
