# Generated by Django 3.2.24 on 2024-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_adddiagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addinvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
            ],
        ),
    ]
