# Generated by Django 3.2.24 on 2024-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_addinvestigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
