# Generated by Django 3.2.24 on 2024-05-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_addfrequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicprofiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic_name', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=100, null=True)),
                ('Address', models.TextField(max_length=1000, null=True)),
                ('Locality', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Tax', models.CharField(max_length=100, null=True)),
                ('Default_language', models.CharField(max_length=1000)),
                ('Date_start', models.DateField()),
                ('Pharmacy_name', models.CharField(max_length=100, null=True)),
                ('Specialization', models.CharField(max_length=100, null=True)),
                ('Mobile_no', models.CharField(max_length=100, null=True)),
                ('Sloga', models.CharField(max_length=100, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=1000, null=True)),
                ('Zip', models.IntegerField()),
                ('Default_Currency', models.CharField(max_length=100)),
                ('Time_zone', models.CharField(max_length=100)),
                ('Pharmacy_licence_code', models.CharField(max_length=100)),
            ],
        ),
    ]
