# Generated by Django 3.2.24 on 2024-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_clinicprofiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicprofiles',
            old_name='Sloga',
            new_name='Slogan',
        ),
    ]
