# Generated by Django 3.2.24 on 2024-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profilepic',
            field=models.ImageField(upload_to='srs'),
        ),
    ]
