# Generated by Django 5.0.6 on 2024-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0013_addlab_addlabtest_addlabtestdeatail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addlaboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labname', models.CharField(max_length=100)),
                ('Labtype', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Executive', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dentalwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workname', models.CharField(max_length=50)),
                ('Shade', models.CharField(max_length=50)),
                ('Worktype', models.CharField(max_length=50)),
                ('Alloytype', models.CharField(max_length=50)),
            ],
        ),
    ]
